INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('38','Image','A beautiful view of Entando Town','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="38"><descr>A beautiful view of Entando Town</descr><groups mainGroup="free" /><categories /><masterfile>Immagine1.jpg</masterfile><instance><size>3</size><filename>Immagine1_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Immagine1_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Immagine1_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>0</size><filename>Immagine1_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>3444 Kb</weight></instance></resource>','Immagine1.jpg',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('17','Image','Stemma','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="17"><descr>Stemma</descr><groups mainGroup="free" /><categories /><masterfile>Building.png</masterfile><instance><size>3</size><filename>Building_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>Building_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>Building_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Building_d0.png</filename><mimetype>image/png</mimetype><weight>3 Kb</weight></instance></resource>','Building.png',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('45','Attach','Statute','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="45"><descr>Statute</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Statute.pdf</masterfile><instance><size>0</size><filename>Entando_Statute.pdf</filename><mimetype>application/pdf</mimetype><weight>289 Kb</weight></instance></resource>','Entando_Statute.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('27','Attach','Resolution 120','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="27"><descr>Resolution 120</descr><groups mainGroup="free" /><categories /><masterfile>Resolution 120.pdf</masterfile><instance><size>0</size><filename>Resolution 120.pdf</filename><mimetype>application/pdf</mimetype><weight>288 Kb</weight></instance></resource>','Resolution 120.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('21','Attach','Announcement for supply of stationery and accessories','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="21"><descr>Announcement for supply of stationery and accessories</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Announcement_Supply_Stationery.pdf</masterfile><instance><size>0</size><filename>Entando_Announcement_Supply_Stationery.pdf</filename><mimetype>application/pdf</mimetype><weight>290 Kb</weight></instance></resource>','Entando_Announcement_Supply_Stationery.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('19','Attach','Announcement for Nautical Institute special maintenance','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="19"><descr>Announcement for Nautical Institute special maintenance</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Announcement_Maintenance_Nautical_Institute.pdf</masterfile><instance><size>0</size><filename>Entando_Announcement_Maintenance_Nautical_Institute.pdf</filename><mimetype>application/pdf</mimetype><weight>289 Kb</weight></instance></resource>','Entando_Announcement_Maintenance_Nautical_Institute.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('49','Attach','Tax - Request ICI refund','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="49"><descr>Tax - Request ICI refund</descr><groups mainGroup="free" /><categories /><masterfile>Tax - Request ICI refund.pdf</masterfile><instance><size>0</size><filename>Tax - Request ICI refund.pdf</filename><mimetype>application/pdf</mimetype><weight>289 Kb</weight></instance></resource>','Tax - Request ICI refund.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('47','Attach','Request Identity Card valid for foreign travel','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="47"><descr>Request Identity Card valid for foreign travel</descr><groups mainGroup="free" /><categories /><masterfile>Request Identity Card valid for foreign travel.pdf</masterfile><instance><size>0</size><filename>Request Identity Card valid for foreign travel.pdf</filename><mimetype>application/pdf</mimetype><weight>290 Kb</weight></instance></resource>','Request Identity Card valid for foreign travel.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('36','Attach','Ground Rent Contribution','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="36"><descr>Ground Rent Contribution</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Ground_Rent_Contribution.pdf</masterfile><instance><size>0</size><filename>Entando_Ground_Rent_Contribution.pdf</filename><mimetype>application/pdf</mimetype><weight>288 Kb</weight></instance></resource>','Entando_Ground_Rent_Contribution.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('31','Attach','Resolution 133','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="31"><descr>Resolution 133</descr><groups mainGroup="free" /><categories /><masterfile>Resolution 133.pdf</masterfile><instance><size>0</size><filename>Resolution 133.pdf</filename><mimetype>application/pdf</mimetype><weight>288 Kb</weight></instance></resource>','Resolution 133.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('25','Attach','Resolution 15','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="25"><descr>Resolution 15</descr><groups mainGroup="free" /><categories /><masterfile>Resolution 15.pdf</masterfile><instance><size>0</size><filename>Resolution 15.pdf</filename><mimetype>application/pdf</mimetype><weight>288 Kb</weight></instance></resource>','Resolution 15.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('29','Attach','Resolution 20','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="29"><descr>Resolution 20</descr><groups mainGroup="free" /><categories /><masterfile>Resolution 20.pdf</masterfile><instance><size>0</size><filename>Resolution 20.pdf</filename><mimetype>application/pdf</mimetype><weight>288 Kb</weight></instance></resource>','Resolution 20.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('51','Attach','Civil Status Self Certification Form','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="51"><descr>Civil Status Self Certification Form</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Civil_Status_Self_Certification_Form.pdf</masterfile><instance><size>0</size><filename>Entando_Civil_Status_Self_Certification_Form.pdf</filename><mimetype>application/pdf</mimetype><weight>289 Kb</weight></instance></resource>','Entando_Civil_Status_Self_Certification_Form.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('53','Attach','Residence Self Certification Form','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="53"><descr>Residence Self Certification Form</descr><groups mainGroup="free" /><categories /><masterfile>Residence Self Certification Form.pdf</masterfile><instance><size>0</size><filename>Residence Self Certification Form.pdf</filename><mimetype>application/pdf</mimetype><weight>289 Kb</weight></instance></resource>','Residence Self Certification Form.pdf',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('42','Image','Mayor','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="42"><descr>Mayor</descr><groups mainGroup="free" /><categories /><masterfile>User_icon.png</masterfile><instance><size>3</size><filename>User_icon_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>User_icon_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>User_icon_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>User_icon_d0.png</filename><mimetype>image/png</mimetype><weight>6 Kb</weight></instance></resource>','User_icon.png',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('73','Image','Council','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="73"><descr>Council</descr><groups mainGroup="free" /><categories /><masterfile>Group_Icon.png</masterfile><instance><size>3</size><filename>Group_Icon_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>Group_Icon_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>Group_Icon_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Group_Icon_d0.png</filename><mimetype>image/png</mimetype><weight>10 Kb</weight></instance></resource>','Group_Icon.png',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('74','Image','Entando town Statute','free','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="74"><descr>Entando town Statute</descr><groups mainGroup="free" /><categories /><masterfile>Statute_icon.png</masterfile><instance><size>3</size><filename>Statute_icon_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>Statute_icon_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>Statute_icon_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Statute_icon_d0.png</filename><mimetype>image/png</mimetype><weight>3 Kb</weight></instance></resource>','Statute_icon.png',NULL,NULL,NULL,NULL,NULL);
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('146','Image','User_icon_Res1.png','reserved_1','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="146"><descr>User_icon_Res1.png</descr><groups mainGroup="reserved_1" /><categories /><masterfile>User_icon_Res1.png</masterfile><metadata-list><metadata id="Filter Method">Adaptive</metadata><metadata id="Detected File Type Long Name">Portable Network Graphics</metadata><metadata id="File Modified Date">Thu Jan 27 12:28:31 +01:00 2022</metadata><metadata id="Compression Type">Deflate</metadata><metadata id="Detected MIME Type">image/png</metadata><metadata id="Expected File Name Extension">png</metadata><metadata id="Image Height">298</metadata><metadata id="Image Width">317</metadata><metadata id="File Size">6454 bytes</metadata><metadata id="Interlace Method">No Interlace</metadata><metadata id="Detected File Type Name">PNG</metadata><metadata id="File Name">User_icon_Res1_d0.png</metadata><metadata id="Color Type">True Color with Alpha</metadata><metadata id="Bits Per Sample">8</metadata></metadata-list><instance><size>0</size><filename>User_icon_Res1_d0.png</filename><mimetype>image/png</mimetype><weight>6 Kb</weight></instance><instance><size>1</size><filename>User_icon_Res1_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>User_icon_Res1_d2.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>3</size><filename>User_icon_Res1_d3.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance></resource>
','User_icon_Res1.png','2022-01-27 12:28:32','2022-01-27 12:28:32',NULL,NULL,'146');
INSERT INTO resources (resid,restype,descr,maingroup,resourcexml,masterfilename,creationdate,lastmodified,owner,folderpath,correlationcode) VALUES ('147','Image','User_icon_Res2.png','reserved_2','<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="147"><descr>User_icon_Res2.png</descr><groups mainGroup="reserved_2" /><categories /><masterfile>User_icon_Res2.png</masterfile><metadata-list><metadata id="Filter Method">Adaptive</metadata><metadata id="Detected File Type Long Name">Portable Network Graphics</metadata><metadata id="File Modified Date">Thu Jan 27 12:28:46 +01:00 2022</metadata><metadata id="Compression Type">Deflate</metadata><metadata id="Detected MIME Type">image/png</metadata><metadata id="Expected File Name Extension">png</metadata><metadata id="Image Height">298</metadata><metadata id="Image Width">317</metadata><metadata id="File Size">6454 bytes</metadata><metadata id="Interlace Method">No Interlace</metadata><metadata id="Detected File Type Name">PNG</metadata><metadata id="File Name">User_icon_Res2_d0.png</metadata><metadata id="Color Type">True Color with Alpha</metadata><metadata id="Bits Per Sample">8</metadata></metadata-list><instance><size>0</size><filename>User_icon_Res2_d0.png</filename><mimetype>image/png</mimetype><weight>6 Kb</weight></instance><instance><size>1</size><filename>User_icon_Res2_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>User_icon_Res2_d2.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>3</size><filename>User_icon_Res2_d3.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance></resource>
','User_icon_Res2.png','2022-01-27 12:28:46','2022-01-27 12:28:46',NULL,NULL,'147');
